"""Open a pull request that adds a result card to the public leaderboard.

Submission friction is the whole ballgame. A contributor who has just run a
benchmark will not fork a repo, clone it, copy a JSON file into the right folder,
commit, push and open a PR by hand — they will close the terminal. So this does
all of it with ``gh``, and when ``gh`` is unavailable it degrades to printing the
exact file and a prefilled URL rather than failing.

Nothing is pushed without validating the card first: a submission that CI would
reject should fail on the contributor's machine, where the error is actionable,
not twenty minutes later in a workflow log.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from pathlib import Path

UPSTREAM = "vijay-kapse/EdgeLLM"
COMMUNITY_PATH = "results/community"
DEFAULT_BRANCH = "main"


class SubmitError(RuntimeError):
    """Submission could not proceed."""


def _run(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=180)


def _gh_available() -> bool:
    if shutil.which("gh") is None:
        return False
    return _run(["gh", "auth", "status"]).returncode == 0


def _manual_instructions(card_path: Path, card: dict) -> str:
    return "\n".join(
        [
            "",
            "GitHub CLI is not available or not signed in, so the PR was not opened for you.",
            "Two ways to finish — both take under a minute:",
            "",
            "  1. Install and sign in, then re-run:",
            "       brew install gh && gh auth login && edge-llm-bench submit",
            "",
            f"  2. Or add the file by hand at https://github.com/{UPSTREAM}/new/{DEFAULT_BRANCH}"
            f"?filename={COMMUNITY_PATH}/{card_path.name}",
            "     and paste the contents of:",
            f"       {card_path}",
            "",
            f"Either way the card describes: {card['machine']['cpu']} · "
            f"{card['model_id']} · {len(card['rows'])} precisions.",
            "",
        ]
    )


def _pr_body(card: dict) -> str:
    machine = card["machine"]
    rows = card["rows"]
    by_precision = {r["precision"]: r for r in rows}
    base = by_precision.get("fp32")

    lines = [
        "Adding a benchmark result card from my machine.",
        "",
        f"- **CPU**: {machine['cpu']} ({machine['arch']}), "
        f"{machine['physical_cores']} physical cores, {machine['ram_gb']:.0f} GB RAM",
        f"- **OS**: {machine['os']} {machine['os_release']}",
        f"- **Runtime**: onnxruntime {machine['onnxruntime']}, {machine['provider']}, "
        f"{machine['intra_op_threads']} threads",
        f"- **Model**: `{card['model_id']}` @ `{card['revision']}`",
        f"- **Tool**: edge-llm-bench {card['tool_version']}",
        "",
        "| Precision | Size (MB) | tok/s | Speedup vs fp32 | Peak RAM (MB) | Perplexity |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        if row["precision"] == "fp32":
            speed = "baseline"
        elif base and base["tokens_per_second"]:
            speed = f"{row['tokens_per_second'] / base['tokens_per_second']:.2f}x"
        else:
            speed = "—"
        ppl = f"{row['perplexity']:.2f}" if row.get("perplexity") else "—"
        lines.append(
            f"| {row['precision']} | {row['size_mb']:.0f} | {row['tokens_per_second']:.2f} | "
            f"{speed} | {row['peak_ram_mb']:.0f} | {ppl} |"
        )

    if card.get("notes"):
        lines += ["", f"**Notes**: {card['notes']}"]

    lines += [
        "",
        "---",
        "",
        "Generated by `edge-llm-bench submit`. The card was validated locally "
        "before this PR was opened.",
    ]
    return "\n".join(lines)


def submit_card(
    card_path: Path,
    *,
    name: str = "",
    notes: str = "",
    dry_run: bool = False,
    echo: Callable[[str], None] = print,
) -> str | None:
    """Validate ``card_path``, then fork-and-PR it upstream. Returns the PR URL."""
    from edgellm.validate import validate_card

    card = json.loads(card_path.read_text())
    if name:
        card["submitted_by"] = name
    if notes:
        card["notes"] = notes
    if name or notes:
        card_path.write_text(json.dumps(card, indent=2, sort_keys=True) + "\n")

    report = validate_card(card_path)
    echo(report.render())
    if not report.ok:
        raise SubmitError(
            "This card would be rejected by CI, so it was not submitted. "
            "Fix the errors above (usually by re-running the benchmark) and try again."
        )

    if dry_run:
        echo("\n--- card (dry run, nothing pushed) ---")
        echo(card_path.read_text())
        echo(f"Would open a PR against {UPSTREAM} adding {COMMUNITY_PATH}/{card_path.name}")
        return None

    if not _gh_available():
        echo(_manual_instructions(card_path, card))
        return None

    slug = card_path.stem
    branch = f"result/{slug}"
    title = f"Results: {card['machine']['cpu']} ({card['machine']['os']}) — {card['model_id']}"

    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp) / "EdgeLLM"
        echo(f"\nForking and cloning {UPSTREAM} ...")

        # `gh repo fork --clone` is idempotent: it reuses an existing fork.
        forked = _run(["gh", "repo", "fork", UPSTREAM, "--clone", "--remote=false", str(workdir)])
        if forked.returncode != 0:
            raise SubmitError(f"could not fork/clone {UPSTREAM}:\n{forked.stderr.strip()}")

        target = workdir / COMMUNITY_PATH
        target.mkdir(parents=True, exist_ok=True)
        shutil.copy2(card_path, target / card_path.name)

        for cmd in (
            ["git", "checkout", "-B", branch],
            ["git", "add", f"{COMMUNITY_PATH}/{card_path.name}"],
        ):
            result = _run(cmd, cwd=workdir)
            if result.returncode != 0:
                raise SubmitError(f"`{' '.join(cmd)}` failed:\n{result.stderr.strip()}")

        staged = _run(["git", "diff", "--cached", "--name-only"], cwd=workdir)
        if not staged.stdout.strip():
            echo(
                "This exact card is already on the leaderboard — nothing to submit. "
                "Re-run the benchmark if you changed something."
            )
            return None

        commit = _run(
            ["git", "commit", "-m", f"Add benchmark results for {card['machine']['cpu']}"],
            cwd=workdir,
        )
        if commit.returncode != 0:
            raise SubmitError(f"commit failed:\n{commit.stderr.strip()}")

        pushed = _run(["git", "push", "-u", "origin", branch, "--force"], cwd=workdir)
        if pushed.returncode != 0:
            raise SubmitError(f"push failed:\n{pushed.stderr.strip()}")

        pr = _run(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                UPSTREAM,
                "--base",
                DEFAULT_BRANCH,
                "--title",
                title,
                "--body",
                _pr_body(card),
            ],
            cwd=workdir,
        )
        if pr.returncode != 0:
            # An open PR from this branch already exists — surface it instead of erroring.
            existing = _run(
                ["gh", "pr", "list", "--repo", UPSTREAM, "--head", branch, "--json", "url"],
                cwd=workdir,
            )
            try:
                urls = json.loads(existing.stdout or "[]")
                if urls:
                    echo(f"\nYour existing PR was updated: {urls[0]['url']}")
                    return urls[0]["url"]
            except json.JSONDecodeError:
                pass
            raise SubmitError(f"could not open the PR:\n{pr.stderr.strip()}")

        url = pr.stdout.strip().splitlines()[-1] if pr.stdout.strip() else ""
        echo(f"\nSubmitted: {url}")
        echo("Thanks — once it merges, your machine appears on the leaderboard.")
        return url
